export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  COMPANY: "COMPANY",
  EMPLOYEE: "EMPLOYEE",
  VIEWER: "VIEWER",
};

export const SUBSCRIPTIONS_TYPES = {
  MONTHLY: "MONTHLY",
  SIX_MONTHS: "SIX_MONTHS",
  YEARLY: "YEARLY",
};

export const TEMPLATE_TYPES = {
  ACCOUNT_CREATION: "ACCOUNT_CREATION",
  ACCOUNT_DELETION: "ACCOUNT_DELETION",
  ACCOUNT_AUTHORIZATION: "ACCOUNT_AUTHORIZATION",
  PASSWORD_RESET: "PASSWORD_RESET",
};

export const OTP_PURPOSES = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  PASSWORD_RESET: "PASSWORD_RESET",
};
